### ISSUE TITLE
Layers Control

### ISSUE THREAD

**Issue by giswqs** [heremaps/here-map-widget-for-jupyter#11]
Does the here map widget have a Layers Control, similar to the ipyleaflet Layers Control? I can't seem to find it on the API Reference. 

https://ipyleaflet.readthedocs.io/en/latest/api_reference/layers_control.html

**Comment by sackh** [comment]
yes, this is an example for layers control - https://here-map-widget-for-jupyter.readthedocs.io/en/stable/api_reference/control/mapsettings.html

**Comment by giswqs** [comment]
Good to know. Thanks.
