### ISSUE TITLE
widget not loading after following installation instructions

### ISSUE THREAD

**Issue by amolnaik** [heremaps/here-map-widget-for-jupyter#2]
Instructions
$ npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/here-node/
$ pip install here-map-widget-for-jupyter
$ jupyter nbextension install –py –sys-prefix here_map_widget
$ jupyter nbextension enable here_map_widget –py –sys-prefix

Code
from here_location_services import LS
from here_map_widget import Map, GeoJSON
ls = LS(api_key=my_key)

address = "Invalidenstr 116, 10115 Berlin, Germany"
gc_response = ls.geocode(query=address)

data = gc_response.to_geojson()
geo_layer = GeoJSON(data=data)

m = Map(api_key=my_key, center=[52.53086, 13.38469], zoom=12)
m.add_layer(geo_layer)
m

does not display map widget

**Comment by sackh** [comment]
Hi @amolnaik 
Will you please provide more details:
1. can you provide the output of the below commands:
   - pip list | grep here-map-widget-for-jupyter
   - pip list | grep here-location-services
   - jupyter nbextension list
2. are you installing here map widget in a separate virtual env or conda env?

**Comment by amolnaik** [comment]
Hi @sackh.

Thanks for a much-awaited widget :) 
The code is working. 
I checked with the NPM repo. Its working with: npm config set registry https://repo.platform.here.com/artifactory/api/npm/here-node/

I used it in place of scoped package. Could that be the reason?

**Comment by sackh** [comment]
I don't think that can be the reason. It is a bit strange. was it only failing for jupyterlab?

**Comment by sackh** [comment]
closing this issue as npm config set command will not be required with a new release of here map widget for jupyter for Jupyter Notebook and JupyterLab 3.
