### ISSUE TITLE
Layout for ipywidgets seems to be ignored

### ISSUE THREAD

**Issue by deeplook** [heremaps/here-map-widget-for-jupyter#7]
It looks like the layout for ipywidgets is not properly handled. I've seen this for buttons (should be square in the example below), but it might happen with other elements, too.

```python
import os
from ipywidgets import Button, Layout
from here_map_widget import Map, DefaultLayers, DefaultLayerNames, WidgetControl

api_key = os.getenv("HEREMAPS_API_KEY")
basemap = DefaultLayers(layer_name=DefaultLayerNames.raster.normal.map)
m = Map(center=[52.5, 13.4], zoom=10, basemap=basemap, api_key=api_key) 
layout = Layout(width="28px", height="28px")
btn = Button(icon="globe", layout=layout)
m.add_control(WidgetControl(widget=btn, alignment="LEFT_TOP"))
m
``` 

<img width="663" alt="Screenshot 2021-03-04 at 09 54 14" src="https://user-images.githubusercontent.com/1001778/109937849-a304b000-7ccf-11eb-93b2-c3bca69cb233.png">

**Comment by sackh** [comment]
Thanks, @deeplook for opening this issue, this will be fixed in the upcoming release.
