### ISSUE TITLE
Support for XYZ and WMS tile layers?

### ISSUE THREAD

**Issue by giswqs** [heremaps/here-map-widget-for-jupyter#9]
Thank you for developing this awesome package. I particularly like the 3D feature, which ipyleaflet is lacking. 

Do you plan to support XYZ and WMS tile layers? I would love to incorporate this package into [geemap](https://geemap.org) if it can support XYZ and WMS tile layers. Thanks.

**Comment by sackh** [comment]
Thanks, @giswqs. we will look into the feasibility of the implementation of these layers. I will share the updates soon.

**Comment by sackh** [comment]
#10 includes support for XYZ Tile layer and regarding WMS, we added support for configuring WMTS data source (that is, the tiled WMS specification)

**Comment by giswqs** [comment]
Thanks a lot for implementing this. I tried to install the package from GitHub on both Windows and Linux, but got the same error  `Could not build wheels for here-map-widget-for-jupyter which use PEP 517 and cannot be installed directly`. Any advice? Thanks. 

![image](https://user-images.githubusercontent.com/5016453/112323853-8d5c2800-8c88-11eb-9317-108dab4637ff.png)

**Comment by sackh** [comment]
did you run the below command before installation? 
`npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/here-node/`

**Comment by giswqs** [comment]
Thanks for the hints! After running the npm command, it works now. I was able to load Google Earth Engine data layers. I look forward to incorporating this into the [geemap](https://github.com/giswqs/geemap/issues/382) package. 

https://gist.github.com/giswqs/2ed65b81dc09def920967a480dbfa8e7

https://user-images.githubusercontent.com/5016453/112339519-1f1e6200-8c96-11eb-97fd-851f7ceaf1c2.mp4
